# queries.py
queries = [
    "Hello",
    "How to make pasta?",
    "Easy Python code",
    "What will the weather be like?",
    "Who are you?",
    "I want to make pasta",
    "How to make pizza?",
    "Can you teach me JavaScript?",
    "Can you teach me Python?",
    "Can you teach me how to make Bolognese pasta?",
    "Teach me how to make pasta",
    "How are you?",
    "How to bake a chocolate cake?",
    "What is the capital of France?",
    "Can you explain quantum physics?",
    "Show me a Python program for data visualization",
    "What are the latest AI trends?",
    "How do I invest in stocks?",
    "Who won the World Cup last year?",
    "How do I solve a Rubik's cube?",
    "Steps to create a new email account",
    "Explain string theory in simple terms",
    "Where is the nearest coffee shop?",
    "How much does the iPhone 15 cost?",
    "Give me a list of top programming languages",
    "What are the health benefits of green tea?",
    "How to write a cover letter for a job?",
    "Who discovered electricity?",
    "What is the tallest building in the world?",
    "How do I improve my resume?",
    "Can you teach me Spanish?",
    "Best hiking trails near me",
    "What is blockchain technology?",
    "Simple exercises for beginners",
    "How to meditate effectively?",
    "Write a poem about autumn",
    "How to calculate ROI in business?",
    "Top 10 movies of all time",
    "Tell me a joke",
    "What's the latest tech news?",
    "How to fix a flat tire?",
    "Can I freeze avocados?",
    "What are the symptoms of flu?",
    "Explain photosynthesis",
    "How to set up a smart home?",
    "Best books on personal finance",
    "Easy vegan recipes for dinner",
    "How to prepare for a job interview?",
    "Write a short story about friendship",
    "What causes climate change?",
    "How to knit a scarf?",
    "Beginner's guide to yoga",
    "What is the meaning of life?",
    "How to start a blog in 2023?",
    "Tips for better sleep",
    "What is the Pythagorean theorem?",
    "How does 5G work?",
    "Most popular pet names",
    "How to improve my handwriting?",
    "Best apps for productivity",
    "What is cryptocurrency mining?",
    "Benefits of intermittent fasting",
    "How to learn guitar on my own?",
    "What are some good self-help books?",
    "Can you explain the Big Bang theory?",
    "How to budget as a college student?",
    "How to become a data scientist?",
    "What is artificial intelligence?",
    "How to make sushi at home?",
    "History of the Roman Empire",
    "Easy DIY home decor ideas",
    "How to draw a realistic eye?",
    "What is machine learning?",
    "How to boost my immune system?",
    "What is mindfulness meditation?",
    "Tips for cooking perfect rice",
    "How to get rid of procrastination?",
    "What is an NFT?",
    "How to save money effectively?",
    "What is digital marketing?",
    "How to create a business plan?",
    "What is an atom made of?",
    "How does the stock market work?",
    "Best ways to recycle at home",
    "How to improve my communication skills?",
    "What are the signs of burnout?",
    "How to plan a road trip?",
    "What is virtual reality?",
    "How to deal with stress?",
    "Simple yoga poses for relaxation",
    "What are the symptoms of anxiety?",
    "Benefits of drinking water daily",
    "How to write a novel?",
    "How to improve public speaking skills?",
    "What are the stages of sleep?",
    "What is the theory of evolution?",
    "How to solve algebraic equations?",
    "What is the speed of light?",
    "Easy ways to learn a new language",
    "What are the benefits of cycling?",
    "How to start a podcast?",
    "Simple steps to declutter your home",
    "What is augmented reality?",
    "How to do a backflip?",
    "What is the Milky Way galaxy?",
    "How to get more followers on social media?",
    "Steps to start a YouTube channel",
    "What is the law of attraction?",
    "How to cook a steak perfectly?",
    "What is genetic engineering?",
    "What is the Fibonacci sequence?",
    "How to find your passion?",
    "How to make a homemade pizza?",
    "What is the periodic table?",
    "How to ace a math test?",
    "What are the benefits of journaling?",
    "How to paint a landscape?",
]
